# Goal: Create a job to run on multiple OS ( Ubuntu and Windows Github runner) environment

name: Cross Operating System Matrix Demonstration

# first define the trigger section like push, pull request, schedule etc
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

    
# second define the jobs you want to run
jobs:
  test-application:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

# NEW STEP: Prints the active OS version and image version

      - name: Display Runner OS Version Details
        shell: bash
        run: |
          echo "======================================================"
          echo "Matrix OS Label: ${{ matrix.os }}"
          echo "Operating System Image: $ImageOS"
          echo "Exact Image Build Version: $ImageVersion"
          echo "======================================================" 

      - name: Setup a Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20'


      - name: Install and Run the app  
        run: |
          npm install
          npm test


